name: OA Data Fetch

on:
  workflow_dispatch:
    inputs:
      script_choice:
        description: 'Select script to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          # - OA_data_fetch_odoo.py
          - OA_ITEM_WISE_data_fetch_odoo.py
          - APR_Combone_Inv_data_fetch.py
          - FG_Dispatch_data_fetch.py
          - AR_Report_combine_invoice.py
  schedule:
    - cron: "*/45 * * * *"  # Every 2 hours daily

jobs:
  fetch-oa-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run selected OA script(s)
        env:
          ODOO_URL: ${{ secrets.ODOO_URL }}
          ODOO_DB: ${{ secrets.ODOO_DB }}
          ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}
          ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          # Fallback to ALL if no input provided (like in scheduled runs)
          SCRIPT_CHOICE="${{ github.event.inputs.script_choice }}"
          if [ -z "$SCRIPT_CHOICE" ]; then
            SCRIPT_CHOICE="ALL"
          fi
          echo "Selected script: $SCRIPT_CHOICE"

          # if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "OA_data_fetch_odoo.py" ]]; then
          #   echo "Running OA_data_fetch_odoo.py..."
          #   python OA_data_fetch_odoo.py
          # fi

          if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "OA_ITEM_WISE_data_fetch_odoo.py" ]]; then
            echo "Running OA_ITEM_WISE_data_fetch_odoo.py..."
            python OA_ITEM_WISE_data_fetch_odoo.py
          fi

          if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "APR_Combone_Inv_data_fetch.py" ]]; then
            echo "Running APR_Combone_Inv_data_fetch.py..."
            python APR_Combone_Inv_data_fetch.py
          fi

          if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "FG_Dispatch_data_fetch.py" ]]; then
            echo "Running FG_Dispatch_data_fetch.py..."
            python FG_Dispatch_data_fetch.py
          fi

          if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "AR_Report_combine_invoice.py" ]]; then
            echo "Running AR_Report_combine_invoice.py..."
            python -u AR_Report_combine_invoice.py
          fi

          if [[ "$SCRIPT_CHOICE" == "ALL" || "$SCRIPT_CHOICE" == "AR_invoice_status_data.py" ]]; then
            echo "Running AR_invoice_status_data.py..."
            python -u AR_invoice_status_data.py
          fi
